### ISSUE TITLE
Bootloop when flashed on esp12 (adafruit huzzah esp8266)

### ISSUE THREAD

**Issue by craftyguy** [Jeija/esp8266-light-alarmclock#2]
Using the esp-open-sdk 2.0, the esp is in what I presume to be a bootloop after building and flashing. I'm a bit at a loss as to how to debug this further. Do you have any suggestions?

**Comment by Jeija** [comment]
I will test and update this repo to esp-open-sdk 2.0 in the next couple of days. I don't know a solution off the top of my head. If I run into this issue while porting to esp-open-sdk 2.0, I'll let you know.

**Comment by craftyguy** [comment]
Actually I JUST figured it out and it was a newbie mistake. I had to update the flash size and speed for the esp12 by modifying the Makefile:

```
FLASH_FREQ              := 40m                                                                                                                                                      
FLASH_MODE              := qio                                                                                                                                                      
FLASH_SIZE              := 512   
FLASH_SIZE_BIT          := 32m                                                                                                                                                    
```

Now to figure out why it's not associating with my wifi AP!

**Comment by Jeija** [comment]
By the way, I just updated the repo for esp-open-sdk 2.0. So in case you were experiencing any issues (especially that undefined-integer-types problem while compiling), you might want to try out the new version. In case you had some issues with API response time, they're now also gone thanks to the latest libesphttpd.

**Comment by craftyguy** [comment]
Oh nice, thank you very much. I'll give this a try
