### ISSUE TITLE
Fritzing for the wiring

### ISSUE THREAD

**Issue by juergenschubert** [Jeija/esp8266-light-alarmclock#4]
Would be great if you could post a concept/ drawing of your wiring.

**Comment by Jeija** [comment]
![schematic](https://user-images.githubusercontent.com/1311964/34913397-7241cb42-f8fc-11e7-82c9-65b54235038d.png)
You basically want to have something similar to this, simply have an n-Channel MOSFET on the low side of the load (e.g. a 12V LED stripe in my case). The resistor and the capacitor make sure the ESP8266's GPIO output is low-pass-filtered before driving the MOSFET. Depending on your MOSFET, you might want have a different setup where the resulting output voltage is divided again (so you have more fine-grained control with the ESP8266's PWM). Also, the resistor / capacitor values depend on how "smooth" you want brightness transitions to be and on your type of MOSFET.

I'm also adding this picture to the README.md
