### ISSUE TITLE
What mosfet where you are using in your circuit?

### ISSUE THREAD

**Issue by juergenschubert** [Jeija/esp8266-light-alarmclock#5]
What mosfet where you are using in your circuit?

**Comment by Jeija** [comment]
IIRC I used the [SD 882](https://www.mouser.com/ds/2/389/2sd882-954337.pdf) NPN transistor. This is *not* a MOSFET and I don't recommend you to use it, it just happened to be the only part I had lying around that had the correct dimensions and was suitable for the current. But really, pretty much any n-Channel MOSFET with a high enough current rating will do.
